services:
  #Mysql
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
      
      # MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}

    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"
  #Laravel
  backend:
    depends_on:
      - db
    build: ./backend
    volumes:
      - ./backend:/container-backend:delegated
      - /container-backend/vendor
    ports:
      - "8000:8000"
    env_file:
      - .env
  #Nextjs
  frontend:
    depends_on:
      - backend
    build: ./frontend
    volumes:
      - ./frontend:/container-frontend:delegated
      - /container-frontend/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env