<?php
namespace Database\Seeders;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class SaizeriyaMenusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table(table: 'menus')->insert([
            ['name' => 'バッファローモッツァレラのピザ', 'number' => 2207, 'price' => 455, 'image_path' => 'saizeriya_img/buffalo_mozzarella.webp', 'description' => 'ミルキーでジューシーなバッファローモッツァレラを贅沢に使用した、本格的なピザです。', 'sweetness' => 1.5, 'sourness' => 2.5, 'saltiness' => 3.5, 'bitterness' => 1.0, 'umami' => 4.0, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'カルボナーラ', 'number' => 2301, 'price' => 455, 'image_path' => 'saizeriya_img/carbonara.webp', 'description' => '卵とチーズ、パンチェッタが織りなす濃厚でクリーミーな味わいが人気の定番パスタです。', 'sweetness' => 1.5, 'sourness' => 1.0, 'saltiness' => 4.0, 'bitterness' => 1.0, 'umami' => 4.5, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'キャンティ', 'number' => 3418, 'price' => 1100, 'image_path' => 'saizeriya_img/chianti.webp', 'description' => 'イタリアの太陽をたっぷり浴びたブドウで造られた、フルーティーで飲みやすい赤ワインです。', 'sweetness' => 2.5, 'sourness' => 3.5, 'saltiness' => 1.0, 'bitterness' => 3.0, 'umami' => 1.5, 'spiciness' => 1.0, 'astringency' => 4.0],
            ['name' => '若鶏のディアボラ風', 'number' => 2402, 'price' => 455, 'image_path' => 'saizeriya_img/chicken_diavola.webp', 'description' => 'パリッと焼き上げた鶏皮と、特製の野菜ソースのピリ辛さが食欲をそそる一品です。', 'sweetness' => 2.0, 'sourness' => 2.0, 'saltiness' => 3.0, 'bitterness' => 1.5, 'umami' => 4.0, 'spiciness' => 3.5, 'astringency' => 1.0],
            ['name' => 'チキンのシーザーサラダ', 'number' => 1206, 'price' => 319, 'image_path' => 'saizeriya_img/chicken_seasar_sarada.webp', 'description' => 'ジューシーなチキンとシャキシャキのレタスを、特製シーザードレッシングでどうぞ。', 'sweetness' => 1.5, 'sourness' => 3.0, 'saltiness' => 3.5, 'bitterness' => 2.0, 'umami' => 3.5, 'spiciness' => 1.0, 'astringency' => 1.5],
            ['name' => 'チョコレートケーキ', 'number' => 3210, 'price' => 273, 'image_path' => 'saizeriya_img/chocolate_cake.webp', 'description' => '濃厚でしっとりとしたチョコレートの風味が口いっぱいに広がる、定番のデザートです。', 'sweetness' => 4.5, 'sourness' => 1.0, 'saltiness' => 1.5, 'bitterness' => 3.0, 'umami' => 1.0, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'チョリソー', 'number' => 1403, 'price' => 364, 'image_path' => 'saizeriya_img/chorizo.webp', 'description' => 'ピリッとした辛さがクセになる、ジューシーなソーセージ。おつまみに最適です。', 'sweetness' => 1.5, 'sourness' => 1.5, 'saltiness' => 4.0, 'bitterness' => 1.5, 'umami' => 4.0, 'spiciness' => 3.5, 'astringency' => 1.0],
            ['name' => 'コーンクリームスープ', 'number' => 1301, 'price' => 137, 'image_path' => 'saizeriya_img/corn_soup.webp', 'description' => 'コーンの自然な甘みが溶け込んだ、優しくてクリーミーな口当たりのスープです。', 'sweetness' => 3.5, 'sourness' => 1.0, 'saltiness' => 2.5, 'bitterness' => 1.0, 'umami' => 2.5, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'デカンタ(500ml)', 'number' => 3403, 'price' => 364, 'image_path' => 'saizeriya_img/dekanta.webp', 'description' => 'みんなでシェアするのにぴったりな500mlサイズのワイン。お得に楽しめます。', 'sweetness' => 2.0, 'sourness' => 3.0, 'saltiness' => 1.0, 'bitterness' => 2.5, 'umami' => 1.5, 'spiciness' => 1.0, 'astringency' => 3.0],
            ['name' => 'ディアボラ風ハンバーグ', 'number' => 2401, 'price' => 455, 'image_path' => 'saizeriya_img/diavola_hamburg.webp', 'description' => 'ジューシーなハンバーグに、特製の野菜ソースをたっぷりかけた人気のメニューです。', 'sweetness' => 2.0, 'sourness' => 2.5, 'saltiness' => 3.5, 'bitterness' => 1.5, 'umami' => 4.5, 'spiciness' => 3.0, 'astringency' => 1.0],
            ['name' => 'エスカルゴのオーブン焼き', 'number' => 4605, 'price' => 364, 'image_path' => 'saizeriya_img/escargot_oven.webp', 'description' => '熱々のガーリックバターソースが食欲をそそる、サイゼリヤの人気前菜です。', 'sweetness' => 1.0, 'sourness' => 1.5, 'saltiness' => 4.0, 'bitterness' => 1.5, 'umami' => 4.5, 'spiciness' => 2.0, 'astringency' => 1.0],
            ['name' => 'グラスワイン', 'number' => 3402, 'price' => 91, 'image_path' => 'saizeriya_img/glass_wine.webp', 'description' => '一杯から気軽に楽しめるハウスワイン。お料理と合わせてどうぞ。', 'sweetness' => 2.0, 'sourness' => 3.0, 'saltiness' => 1.0, 'bitterness' => 2.5, 'umami' => 1.5, 'spiciness' => 1.0, 'astringency' => 3.0],
            ['name' => 'ハンバーグステーキ', 'number' => 2408, 'price' => 364, 'image_path' => 'saizeriya_img/hamburg.webp', 'description' => '牛肉100%のジューシーなハンバーグ。肉の旨みを存分に味わえる一品です。', 'sweetness' => 1.5, 'sourness' => 1.5, 'saltiness' => 3.5, 'bitterness' => 1.0, 'umami' => 4.5, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'イタリアンジェラート', 'number' => 3205, 'price' => 228, 'image_path' => 'saizeriya_img/italian_gelato.webp', 'description' => 'ミルクの風味が豊かな、なめらかな口溶けの本格ジェラートです。', 'sweetness' => 4.0, 'sourness' => 1.0, 'saltiness' => 1.5, 'bitterness' => 1.0, 'umami' => 1.0, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'イタリアンハンバーグ', 'number' => 2403, 'price' => 455, 'image_path' => 'saizeriya_img/italian_hamburg.webp', 'description' => 'とろーりチーズと特製トマトソースが、ジューシーなハンバーグと絶妙にマッチします。', 'sweetness' => 2.5, 'sourness' => 3.0, 'saltiness' => 3.5, 'bitterness' => 1.0, 'umami' => 4.5, 'spiciness' => 1.5, 'astringency' => 1.0],
            ['name' => 'ランブルスコ ロゼ', 'number' => 3412, 'price' => 1100, 'image_path' => 'saizeriya_img/lambrusco_lose.webp', 'description' => '華やかな香りと優しい甘さが特徴の、微発泡ロゼワインです。', 'sweetness' => 3.5, 'sourness' => 3.0, 'saltiness' => 1.0, 'bitterness' => 2.0, 'umami' => 1.0, 'spiciness' => 1.0, 'astringency' => 2.0],
            ['name' => 'ランブルスコ セッコ', 'number' => 3413, 'price' => 1100, 'image_path' => 'saizeriya_img/lambrusco_secco.webp', 'description' => 'すっきりとした辛口で、どんな料理にも合わせやすい微発泡の赤ワインです。', 'sweetness' => 1.5, 'sourness' => 3.5, 'saltiness' => 1.0, 'bitterness' => 3.0, 'umami' => 1.5, 'spiciness' => 1.0, 'astringency' => 3.5],
            ['name' => 'マグナム(1500ml)', 'number' => 3407, 'price' => 1100, 'image_path' => 'saizeriya_img/magnum.webp', 'description' => '通常のボトル2本分の大容量。大人数でのパーティーに最適です。', 'sweetness' => 2.0, 'sourness' => 3.0, 'saltiness' => 1.0, 'bitterness' => 2.5, 'umami' => 1.5, 'spiciness' => 1.0, 'astringency' => 3.0],
            ['name' => 'マルゲリータピザ', 'number' => 2201, 'price' => 364, 'image_path' => 'saizeriya_img/margherita_pizza.webp', 'description' => 'トマト、モッツァレラ、バジルが彩る、シンプルながらも王道のイタリアンピザです。', 'sweetness' => 2.0, 'sourness' => 3.0, 'saltiness' => 3.0, 'bitterness' => 1.5, 'umami' => 3.5, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'ミートソースボロニア風', 'number' => 2306, 'price' => 364, 'image_path' => 'saizeriya_img/meat_spaghetti.webp', 'description' => 'じっくり煮込んだ牛肉と香味野菜の旨みが凝縮された、コク深い味わいのパスタです。', 'sweetness' => 2.5, 'sourness' => 2.5, 'saltiness' => 3.5, 'bitterness' => 1.5, 'umami' => 4.5, 'spiciness' => 1.5, 'astringency' => 1.0],
            ['name' => 'ミニフィセル', 'number' => 3110, 'price' => 137, 'image_path' => 'saizeriya_img/mini_ficelle.webp', 'description' => '外はパリッ、中はもっちりとした食感の小さなフランスパン。お料理のお供にどうぞ。', 'sweetness' => 1.5, 'sourness' => 1.0, 'saltiness' => 2.5, 'bitterness' => 1.0, 'umami' => 2.0, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'ミラノ風ドリア', 'number' => 2101, 'price' => 273, 'image_path' => 'saizeriya_img/mirano_doria.webp', 'description' => 'クリーミーなホワイトソースとミートソースが絶妙な、創業以来愛され続ける看板メニューです。', 'sweetness' => 2.5, 'sourness' => 1.5, 'saltiness' => 3.5, 'bitterness' => 1.0, 'umami' => 4.0, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'ソーセージピザ', 'number' => 2208, 'price' => 364, 'image_path' => 'saizeriya_img/mozzarella_pizza.webp', 'description' => 'ジューシーなソーセージとコーンがたっぷり乗った、子どもから大人まで楽しめるピザです。', 'sweetness' => 3.0, 'sourness' => 2.0, 'saltiness' => 3.5, 'bitterness' => 1.0, 'umami' => 4.0, 'spiciness' => 2.0, 'astringency' => 1.0],
            ['name' => 'ペペロンチーノ', 'number' => 2302, 'price' => 273, 'image_path' => 'saizeriya_img/peperoncino.webp', 'description' => 'ニンニクの香りと唐辛子のピリ辛さが引き立つ、シンプルで奥深い味わいのパスタです。', 'sweetness' => 1.0, 'sourness' => 1.0, 'saltiness' => 3.0, 'bitterness' => 1.5, 'umami' => 3.5, 'spiciness' => 4.0, 'astringency' => 1.0],
            ['name' => 'ポップコーンシュリンプ', 'number' => 1404, 'price' => 273, 'image_path' => 'saizeriya_img/popcorn_shrimp.webp', 'description' => 'サクサクの衣とプリプリのエビの食感が楽しい、ついつい手が伸びる一品です。', 'sweetness' => 1.5, 'sourness' => 1.5, 'saltiness' => 3.5, 'bitterness' => 1.0, 'umami' => 4.0, 'spiciness' => 1.5, 'astringency' => 1.0],
            ['name' => 'プチフォッカ', 'number' => 4610, 'price' => 137, 'image_path' => 'saizeriya_img/puchi_focacio.webp', 'description' => 'ふんわりとした食感の小さなフォカッチャ。そのままでも、料理と一緒でも美味しいです。', 'sweetness' => 1.5, 'sourness' => 1.0, 'saltiness' => 2.5, 'bitterness' => 1.0, 'umami' => 2.0, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'プリンとティラミス クラシコの盛合せ', 'number' => 3240, 'price' => 455, 'image_path' => 'saizeriya_img/purine_tiramisu.webp', 'description' => 'なめらかなプリンとほろ苦いティラミス、二つの人気デザートを一度に楽しめます。', 'sweetness' => 4.0, 'sourness' => 1.0, 'saltiness' => 1.5, 'bitterness' => 2.5, 'umami' => 1.0, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'ライス', 'number' => 3101, 'price' => 137, 'image_path' => 'saizeriya_img/rice.webp', 'description' => 'ふっくらと炊き上げたライス。ハンバーグやチキンとご一緒にどうぞ。', 'sweetness' => 1.0, 'sourness' => 1.0, 'saltiness' => 1.5, 'bitterness' => 1.0, 'umami' => 1.5, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'エビクリームグラタン', 'number' => 2105, 'price' => 364, 'image_path' => 'saizeriya_img/shrimp_gratin.webp', 'description' => 'エビの旨みが溶け込んだクリーミーなホワイトソースと、ペンネの相性が抜群です。', 'sweetness' => 2.0, 'sourness' => 1.5, 'saltiness' => 3.5, 'bitterness' => 1.0, 'umami' => 4.0, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => '小エビのサラダ', 'number' => 1202, 'price' => 319, 'image_path' => 'saizeriya_img/shrimp_sarada.webp', 'description' => 'たっぷり入った甘エビと、特製ドレッシングの酸味がよく合います。', 'sweetness' => 2.5, 'sourness' => 3.0, 'saltiness' => 2.5, 'bitterness' => 1.5, 'umami' => 3.0, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => '辛味チキン', 'number' => 1401, 'price' => 273, 'image_path' => 'saizeriya_img/spicy_chicken.webp', 'description' => '絶妙なスパイスで味付けした手羽中。やみつきになる美味しさで、お酒も進みます。', 'sweetness' => 1.5, 'sourness' => 1.5, 'saltiness' => 3.5, 'bitterness' => 1.5, 'umami' => 4.0, 'spiciness' => 4.0, 'astringency' => 1.0],
            ['name' => 'イカの墨入りスパゲッティ', 'number' => 2320, 'price' => 455, 'image_path' => 'saizeriya_img/squid_ink_spaghetti.webp', 'description' => 'イカ墨のコクと旨みを存分に引き出した、見た目も味もインパクトのある一皿です。', 'sweetness' => 1.0, 'sourness' => 1.5, 'saltiness' => 4.0, 'bitterness' => 2.0, 'umami' => 4.5, 'spiciness' => 2.0, 'astringency' => 1.0],
            ['name' => 'タラコソースシシリー風', 'number' => 2303, 'price' => 364, 'image_path' => 'saizeriya_img/tarako_spaghetti.webp', 'description' => 'たっぷりのタラコソースと刻み海苔の風味が豊かな、人気の和風パスタです。', 'sweetness' => 1.5, 'sourness' => 1.0, 'saltiness' => 4.0, 'bitterness' => 1.0, 'umami' => 4.5, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'ティラミス クラシコ', 'number' => 3201, 'price' => 273, 'image_path' => 'saizeriya_img/tiramisu.webp', 'description' => 'マスカルポーネチーズの豊かな風味と、ココアパウダーのほろ苦さが絶妙なデザートです。', 'sweetness' => 4.0, 'sourness' => 1.0, 'saltiness' => 1.5, 'bitterness' => 3.0, 'umami' => 1.5, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => 'トリフアイスクリーム', 'number' => 3232, 'price' => 319, 'image_path' => 'saizeriya_img/truffe_ice_cream.webp', 'description' => '濃厚なチョコレートアイスの中に、とろりとしたチョコレートソースが入った贅沢な一品です。', 'sweetness' => 4.5, 'sourness' => 1.0, 'saltiness' => 1.5, 'bitterness' => 2.5, 'umami' => 1.0, 'spiciness' => 1.0, 'astringency' => 1.0],
            ['name' => '生ビール(中ジョッキ)', 'number' => 3301, 'price' => 364, 'image_path' => 'saizeriya_img/tyu_zyokki.webp', 'description' => 'キリッと冷えた喉越し爽快な生ビール。どんな料理とも相性抜群です。', 'sweetness' => 1.5, 'sourness' => 2.0, 'saltiness' => 1.0, 'bitterness' => 3.5, 'umami' => 1.5, 'spiciness' => 1.0, 'astringency' => 2.0],
            ['name' => 'ヴェルデッキオ', 'number' => 3415, 'price' => 1100, 'image_path' => 'saizeriya_img/verdecchio.webp', 'description' => 'フレッシュでフルーティーな香りが特徴の、すっきりとした辛口の白ワインです。', 'sweetness' => 1.5, 'sourness' => 4.0, 'saltiness' => 1.0, 'bitterness' => 2.0, 'umami' => 1.0, 'spiciness' => 1.0, 'astringency' => 2.5],
        ]);
    }
}